data = {
        "Passmark": {
            "en": "It is part of the Passmark PerformanceTest suite and probably the most common benchmark. This benchmark evaluates the graphic card under different loads. It provides four benchmarks, each for Direct3D version 9, 11, and 12, with the last one in 4K resolution. There are also a few other DirectCompute-related tests.",
            "de": "Es ist Teil der Passmark PerformanceTest-Suite und wahrscheinlich der häufigste Benchmark. Dieser Benchmark bewertet die Grafikkarte unter verschiedenen Lasten. Es bietet vier Benchmarks, jeweils für die Direct3D-Versionen 9, 11 und 12, der letzte in 4K-Auflösung. Es gibt auch einige andere DirectCompute-bezogene Tests.",
            "es": "Es parte de la suite Passmark PerformanceTest y probablemente el punto de referencia más común. Este benchmark evalúa la tarjeta gráfica bajo diferentes cargas. Proporciona cuatro puntos de referencia, cada uno para Direct3D versión 9, 11 y 12, con el último en resolución 4K. También hay algunas otras pruebas relacionadas con DirectCompute.",
            "fr": "Il fait partie de la suite Passmark PerformanceTest et est probablement la référence la plus courante. Ce benchmark évalue la carte graphique sous différentes charges. Il fournit quatre benchmarks, chacun pour les versions 9, 11 et 12 de Direct3D, le dernier en résolution 4K. Il existe également quelques autres tests liés à DirectCompute.",
            "tr": "Passmark PerformanceTest paketinin bir parçasıdır ve muhtemelen en yaygın kıyaslamadır. Bu kıyaslama, grafik kartını farklı yükler altında değerlendirir. Her biri Direct3D sürüm 9, 11 ve 12 için ve sonuncusu 4K çözünürlükte olmak üzere dört kıyaslama sağlar. DirectCompute ile ilgili başka birkaç test de vardır.",
            "zh": "它是 Passmark PerformanceTest 套件的一部分，可能是最常见的基准测试。该基准测试评估了不同负载下的图形卡。它提供了四个基准测试，每个用于 Direct3D 版本 9、11 和 12，最后一个用于 4K 分辨率。还有其他一些与 DirectCompute 相关的测试。",
            "hi": "यह Passmark PerformanceTest सुइट का हिस्सा है और शायद सबसे आम बेंचमार्क है। यह बेंचमार्क विभिन्न भारों के तहत ग्राफिक कार्ड का मूल्यांकन करता है। यह चार बेंचमार्क प्रदान करता है, प्रत्येक Direct3D संस्करण 9, 11 और 12 के लिए, 4K रिज़ॉल्यूशन में अंतिम के साथ। DirectCompute से संबंधित कुछ अन्य परीक्षण भी हैं।"
        },
 
        "3DMark Vantage Performance": {
            "en": "3DMark Vantage, an obsolete DirectX 10 benchmark that uses 1280x1024 screen resolution, is called. The 2DMark Vantage taxes the graphics card by showing two scenes. One shows a girl fleeing from a militarized base within a cave. Another depicts a fleet of spaceships attacking a planet defenseless. In April 2017, it was removed. Instead, Time Spy benchmark should be used.",
            "de": "3DMark Vantage wird aufgerufen, ein veralteter DirectX-10-Benchmark, der eine Bildschirmauflösung von 1280 x 1024 verwendet. Der 2DMark Vantage fordert die Grafikkarte, indem er zwei Szenen zeigt. Eines zeigt ein Mädchen, das von einer militarisierten Basis in einer Höhle flieht. Ein anderer zeigt eine Flotte von Raumschiffen, die einen Planeten wehrlos angreifen. Im April 2017 wurde es entfernt. Stattdessen sollte der Time Spy-Benchmark verwendet werden.",
            "es": "Se llama 3DMark Vantage, un punto de referencia de DirectX 10 obsoleto que utiliza una resolución de pantalla de 1280x1024. El 2DMark Vantage pone a prueba la tarjeta gráfica mostrando dos escenas. Uno muestra a una niña que huye de una base militarizada dentro de una cueva. Otro representa una flota de naves espaciales atacando un planeta indefenso. En abril de 2017, se eliminó. En su lugar, se debe utilizar el punto de referencia de Time Spy.",
            "fr": "3DMark Vantage, un benchmark DirectX 10 obsolète qui utilise une résolution d'écran de 1280x1024, est appelé. Le 2DMark Vantage taxe la carte graphique en affichant deux scènes. L'un montre une fille fuyant une base militarisée dans une grotte. Un autre représente une flotte de vaisseaux spatiaux attaquant une planète sans défense. En avril 2017, il a été supprimé. Au lieu de cela, le benchmark Time Spy doit être utilisé.",
            "tr": "1280x1024 ekran çözünürlüğü kullanan eski bir DirectX 10 kıyaslaması olan 3DMark Vantage denir. 2DMark Vantage, iki sahne göstererek grafik kartını zorlar. Biri, bir mağaranın içindeki militarize edilmiş bir üsten kaçan bir kızı gösteriyor. Bir diğeri, savunmasız bir gezegene saldıran bir uzay gemisi filosunu tasvir ediyor. Nisan 2017'de kaldırıldı. Bunun yerine, Time Spy kıyaslaması kullanılmalıdır.",
            "zh": "称为 3DMark Vantage，这是一种使用 1280x1024 屏幕分辨率的过时 DirectX 10 基准测试。 2DMark Vantage 通过显示两个场景对显卡进行测试。一个显示一个女孩从洞穴内的军事化基地逃离。另一幅描绘了一队宇宙飞船攻击一个毫无防御能力的行星。 2017 年 4 月，它被删除了。相反，应该使用 Time Spy 基准测试。",
            "hi": "3DMark सहूलियत, एक अप्रचलित DirectX 10 बेंचमार्क जो 1280x1024 स्क्रीन रिज़ॉल्यूशन का उपयोग करता है, को कहा जाता है। 2DMark सहूलियत दो दृश्यों को दिखा कर ग्राफिक्स कार्ड पर कर लगाती है। एक गुफा के भीतर एक सैन्य ठिकाने से एक लड़की को भागते हुए दिखाया गया है। दूसरे में अंतरिक्ष यान के एक बेड़े को रक्षाहीन ग्रह पर हमला करते हुए दर्शाया गया है। अप्रैल 2017 में इसे हटा दिया गया था। इसके बजाय, टाइम स्पाई बेंचमार्क का उपयोग किया जाना चाहिए।"
        }
        ,

        "3DMark 11 Performance GPU": {
            "en": "Futuremark's 3DMark 11 benchmark is obsolete DirectX 11. The four scenes used in this test were two: a few submersibles searching the wreck of a sunken vessel, and an abandoned temple deep within the jungle. The tests, which are done at 1280x720 resolution and require volumetric lighting, tessellation and heavy computations, can be quite taxing. 3DMark 11 was discontinued in January 2020. Time Spy has now taken over.",
            "de": "Der 3DMark 11-Benchmark von Futuremark ist veraltetes DirectX 11. Die vier Szenen, die in diesem Test verwendet wurden, waren zwei: ein paar Tauchboote, die das Wrack eines gesunkenen Schiffes durchsuchen, und ein verlassener Tempel tief im Dschungel. Die Tests, die mit einer Auflösung von 1280 x 720 durchgeführt werden und volumetrische Beleuchtung, Tessellation und umfangreiche Berechnungen erfordern, können ziemlich anstrengend sein. 3DMark 11 wurde im Januar 2020 eingestellt. Time Spy hat nun übernommen.",
            "es": "El punto de referencia 3DMark 11 de Futuremark es DirectX 11 obsoleto. Las cuatro escenas utilizadas en esta prueba fueron dos: unos pocos sumergibles buscando los restos de un barco hundido y un templo abandonado en lo profundo de la jungla. Las pruebas, que se realizan con una resolución de 1280x720 y requieren iluminación volumétrica, teselado y cálculos pesados, pueden ser bastante exigentes. 3DMark 11 se suspendió en enero de 2020. Time Spy ahora se ha hecho cargo.",
            "fr": "Le benchmark 3DMark 11 de Futuremark est DirectX 11 obsolète. Les quatre scènes utilisées dans ce test étaient deux : quelques submersibles fouillant l'épave d'un navire coulé et un temple abandonné au plus profond de la jungle. Les tests, qui sont effectués à une résolution de 1280x720 et nécessitent un éclairage volumétrique, une tessellation et des calculs lourds, peuvent être assez éprouvants. 3DMark 11 a été arrêté en janvier 2020. Time Spy a maintenant pris le relais.",
            "tr": "Futuremark'ın 3DMark 11 kriteri, eski DirectX 11'dir. Bu testte kullanılan dört sahne iki idi: batık bir geminin enkazını arayan birkaç denizaltı ve ormanın derinliklerinde terk edilmiş bir tapınak. 1280x720 çözünürlükte yapılan ve hacimsel aydınlatma, mozaikleme ve ağır hesaplamalar gerektiren testler oldukça zahmetli olabilir. 3DMark 11, Ocak 2020'de kullanımdan kaldırıldı. Şimdi Time Spy devraldı.",
            "zh": "Futuremark 的 3DMark 11 基准测试是过时的 DirectX 11。此测试中使用的四个场景是两个：几艘潜水器搜索沉船残骸，以及丛林深处一座废弃的寺庙。这些测试在 1280x720 分辨率下完成，需要体积光照、曲面细分和大量计算，可能会非常费力。 3DMark 11 于 2020 年 1 月停产。Time Spy 现已接管。",
            "hi": "Futuremark का 3DMark 11 बेंचमार्क अप्रचलित DirectX 11 है। इस परीक्षण में उपयोग किए गए चार दृश्य दो थे: कुछ पनडुब्बियां डूबे हुए जहाज के मलबे की खोज कर रही थीं, और जंगल के भीतर एक परित्यक्त मंदिर। परीक्षण, जो 1280x720 रिज़ॉल्यूशन पर किए जाते हैं और इसके लिए वॉल्यूमेट्रिक लाइटिंग, टेसलेशन और भारी संगणना की आवश्यकता होती है, काफी कर योग्य हो सकते हैं। 3DMark 11 को जनवरी 2020 में बंद कर दिया गया था। टाइम स्पाई ने अब इसे संभाल लिया है।"
        },

        "3DMark Fire Strike Graphics": {
            "en": "Fire Strike, a DirectX 11 benchmark is available for gaming computers. Two separate tests are featured, one showing a battle between two humanoids and another featuring a fiery creature made from lava. Fire Strike has a 1920x1080 resolution and can be quite demanding on your hardware.",
            "de": "Fire Strike, ein DirectX 11-Benchmark, ist für Gaming-Computer verfügbar. Es werden zwei separate Tests vorgestellt, einer zeigt einen Kampf zwischen zwei Humanoiden und der andere eine feurige Kreatur aus Lava. Fire Strike hat eine Auflösung von 1920 x 1080 und kann für Ihre Hardware ziemlich anspruchsvoll sein.",
            "es": "Fire Strike, un punto de referencia de DirectX 11 está disponible para computadoras de juegos. Se presentan dos pruebas separadas, una que muestra una batalla entre dos humanoides y otra con una criatura ardiente hecha de lava. Fire Strike tiene una resolución de 1920x1080 y puede ser bastante exigente con su hardware.",
            "fr": "Fire Strike, un benchmark DirectX 11 est disponible pour les ordinateurs de jeu. Deux tests distincts sont présentés, l'un montrant une bataille entre deux humanoïdes et l'autre mettant en vedette une créature ardente faite de lave. Fire Strike a une résolution de 1920x1080 et peut être assez exigeant pour votre matériel.",
            "tr": "Oyun bilgisayarları için bir DirectX 11 kıyaslaması olan Fire Strike mevcuttur. Biri iki insansı arasındaki savaşı gösteren, diğeri ise lavdan yapılmış ateşli bir yaratığı gösteren iki ayrı test yer alıyor. Fire Strike, 1920x1080 çözünürlüğe sahiptir ve donanımınızı oldukça zorlayabilir.",
            "zh": "Fire Strike 是一款适用于游戏电脑的 DirectX 11 基准测试。有两个独立的测试，一个显示两个类人动物之间的战斗，另一个显示由熔岩制成的炽热生物。 Fire Strike 的分辨率为 1920x1080，对您的硬件要求很高。",
            "hi": "फायर स्ट्राइक, एक DirectX 11 बेंचमार्क गेमिंग कंप्यूटर के लिए उपलब्ध है। दो अलग-अलग परीक्षणों को चित्रित किया गया है, एक में दो ह्यूमनॉइड्स के बीच लड़ाई दिखाई गई है और दूसरे में लावा से बने एक उग्र प्राणी की विशेषता है। फायर स्ट्राइक का 1920x1080 रिज़ॉल्यूशन है और आपके हार्डवेयर पर काफी मांग हो सकती है।"
        },

        "3DMark Cloud Gate GPU": {
            "en": "Cloud Gate was an old DirectX 11 benchmark at feature level 10, which was intended for basic notebooks and home computers. This shows a couple of scenes from a strange space teleportation device that launches spaceships into the unknown. It uses 720x1280 pixels. It was replaced in January 2020 by 3DMark Night Raid, just like Ice Storm benchmark.",
            "de": "Cloud Gate war ein alter DirectX-11-Benchmark auf Feature-Level 10, der für einfache Notebooks und Heimcomputer gedacht war. Dies zeigt ein paar Szenen von einem seltsamen Weltraum-Teleportationsgerät, das Raumschiffe ins Unbekannte schickt. Es verwendet 720 x 1280 Pixel. Es wurde im Januar 2020 durch 3DMark Night Raid ersetzt, genau wie der Ice Storm-Benchmark.",
            "es": "Cloud Gate era un antiguo punto de referencia de DirectX 11 en el nivel de características 10, que estaba destinado a computadoras portátiles básicas y computadoras domésticas. Esto muestra un par de escenas de un extraño dispositivo de teletransportación espacial que lanza naves espaciales hacia lo desconocido. Utiliza 720x1280 píxeles. Fue reemplazado en enero de 2020 por 3DMark Night Raid, al igual que el punto de referencia de Ice Storm.",
            "fr": "Cloud Gate était une ancienne référence DirectX 11 au niveau de fonctionnalité 10, qui était destinée aux ordinateurs portables de base et aux ordinateurs personnels. Cela montre quelques scènes d'un étrange appareil de téléportation spatiale qui lance des vaisseaux spatiaux dans l'inconnu. Il utilise 720x1280 pixels. Il a été remplacé en janvier 2020 par 3DMark Night Raid, tout comme le benchmark Ice Storm.",
            "tr": "It is part of the Passmark PerformanceTest suite and probably the most common benchmark.",
            "zh": "Cloud Gate 是功能级别 10 的旧 DirectX 11 基准测试，适用于基本笔记本电脑和家用电脑。这显示了一个奇怪的太空传送装置的几个场景，该装置将宇宙飞船发射到未知的地方。它使用 720x1280 像素。它在 2020 年 1 月被 3DMark Night Raid 取代，就像 Ice Storm 基准测试一样。",
            "hi": "क्लाउड गेट सुविधा स्तर 10 पर एक पुराना DirectX 11 बेंचमार्क था, जो मूल नोटबुक और होम कंप्यूटर के लिए अभिप्रेत था। यह एक अजीब अंतरिक्ष टेलीपोर्टेशन डिवाइस से कुछ दृश्यों को दिखाता है जो अंतरिक्ष यान को अज्ञात में लॉन्च करता है। यह 720x1280 पिक्सल का उपयोग करता है। इसे आइस स्टॉर्म बेंचमार्क की तरह जनवरी 2020 में 3DMark नाइट रेड द्वारा बदल दिया गया था।"
        },

        "3DMark Ice Storm GPU": {
            "en": "Ice Storm Graphics, an outdated benchmark that is part of 3DMark suite, can be found here. Ice Storm was designed to assess the performance of entry-level laptops and Windows tablets. DirectX 11 feature 9 is used to show a battle between space ships near a frozen planet at 1280x720 resolution. It was discontinued in January 2020 and replaced by 3DMark Night Raid.",
            "de": "Ice Storm Graphics, ein veralteter Benchmark, der Teil der 3DMark-Suite ist, finden Sie hier. Ice Storm wurde entwickelt, um die Leistung von Laptops und Windows-Tablets der Einstiegsklasse zu bewerten. DirectX 11 Feature 9 wird verwendet, um einen Kampf zwischen Raumschiffen in der Nähe eines gefrorenen Planeten mit einer Auflösung von 1280 x 720 zu zeigen. Es wurde im Januar 2020 eingestellt und durch 3DMark Night Raid ersetzt.",
            "es": "Ice Storm Graphics, un punto de referencia obsoleto que forma parte de la suite 3DMark, se puede encontrar aquí. Ice Storm fue diseñado para evaluar el rendimiento de las computadoras portátiles de nivel de entrada y las tabletas de Windows. La función 9 de DirectX 11 se utiliza para mostrar una batalla entre naves espaciales cerca de un planeta congelado con una resolución de 1280x720. Se suspendió en enero de 2020 y se reemplazó por 3DMark Night Raid.",
            "fr": "Ice Storm Graphics, une référence obsolète qui fait partie de la suite 3DMark, peut être trouvée ici. Ice Storm a été conçu pour évaluer les performances des ordinateurs portables d'entrée de gamme et des tablettes Windows. La fonctionnalité 9 de DirectX 11 est utilisée pour montrer une bataille entre des vaisseaux spatiaux près d'une planète gelée à une résolution de 1280x720. Il a été interrompu en janvier 2020 et remplacé par 3DMark Night Raid.",
            "tr": "3DMark paketinin bir parçası olan eski bir karşılaştırma testi olan Ice Storm Graphics burada bulunabilir. Ice Storm, giriş seviyesi dizüstü bilgisayarların ve Windows tabletlerin performansını değerlendirmek için tasarlanmıştır. DirectX 11 özellik 9, donmuş bir gezegenin yakınında uzay gemileri arasındaki savaşı 1280x720 çözünürlükte göstermek için kullanılır. Ocak 2020'de durduruldu ve yerini 3DMark Night Raid aldı.",
            "zh": "Ice Storm Graphics 是 3DMark 套件中的一个过时基准测试，可在此处找到。 Ice Storm 旨在评估入门级笔记本电脑和 Windows 平板电脑的性能。 DirectX 11 功能 9 用于以 1280x720 分辨率显示冰冻行星附近太空船之间的战斗。它于 2020 年 1 月停产，取而代之的是 3DMark Night Raid。",
            "hi": "आइस स्टॉर्म ग्राफिक्स, एक पुराना बेंचमार्क जो 3DMark सूट का हिस्सा है, यहां पाया जा सकता है। आइस स्टॉर्म को प्रवेश स्तर के लैपटॉप और विंडोज टैबलेट के प्रदर्शन का आकलन करने के लिए डिजाइन किया गया था। DirectX 11 फीचर 9 का उपयोग 1280x720 रिज़ॉल्यूशन पर जमे हुए ग्रह के पास अंतरिक्ष यान के बीच लड़ाई दिखाने के लिए किया जाता है। इसे जनवरी 2020 में बंद कर दिया गया और इसकी जगह 3DMark नाइट रेड ने ले ली।"
        },

        "Unigine Heaven 3.0": {
            "en": "This benchmark uses DirectX 11 and Unigine (a 3D engine developed by the eponymous Russian firm). The image depicts a fictional medieval city spread over many flying islands. In 2012, Version 3.0 was launched. However, Heaven 4.0 was released in 2013. It introduced several minor improvements including a more recent version of Unigine.",
            "de": "Dieser Benchmark verwendet DirectX 11 und Unigine (eine 3D-Engine, die von der gleichnamigen russischen Firma entwickelt wurde). Das Bild zeigt eine fiktive mittelalterliche Stadt, die sich über viele fliegende Inseln erstreckt. 2012 wurde die Version 3.0 eingeführt. Heaven 4.0 wurde jedoch 2013 veröffentlicht. Es führte mehrere kleinere Verbesserungen ein, darunter eine neuere Version von Unigine.",
            "es": "Este banco de pruebas utiliza DirectX 11 y Unigine (un motor 3D desarrollado por la firma rusa del mismo nombre). La imagen representa una ciudad medieval ficticia repartida en muchas islas voladoras. En 2012, se lanzó la Versión 3.0. Sin embargo, Heaven 4.0 se lanzó en 2013. Introdujo varias mejoras menores, incluida una versión más reciente de Unigine.",
            "fr": "Ce benchmark utilise DirectX 11 et Unigine (un moteur 3D développé par la firme russe éponyme). L'image représente une ville médiévale fictive répartie sur de nombreuses îles volantes. En 2012, la version 3.0 a été lancée. Cependant, Heaven 4.0 est sorti en 2013. Il a introduit plusieurs améliorations mineures, dont une version plus récente d'Unigine.",
            "tr": "Bu kıyaslama, DirectX 11 ve Unigine (adını taşıyan Rus firması tarafından geliştirilen bir 3D motor) kullanır. Görüntü, birçok uçan adaya yayılmış kurgusal bir ortaçağ şehrini tasvir ediyor. 2012'de Sürüm 3.0 piyasaya sürüldü. Ancak Heaven 4.0, 2013'te piyasaya sürüldü. Unigine'nin daha yeni bir sürümü de dahil olmak üzere birkaç küçük iyileştirme getirdi.",
            "zh": "该基准测试使用 DirectX 11 和 Unigine（由同名俄罗斯公司开发的 3D 引擎）。该图像描绘了一个虚构的中世纪城市，分布在许多飞行岛屿上。 2012年，推出3.0版本。然而，Heaven 4.0 于 2013 年发布。它引入了几项小改进，包括更新版本的 Unigine。",
            "hi": "यह बेंचमार्क DirectX 11 और Unigine (नामांकित रूसी फर्म द्वारा विकसित एक 3D इंजन) का उपयोग करता है। छवि कई उड़ने वाले द्वीपों में फैले एक काल्पनिक मध्ययुगीन शहर को दर्शाती है। 2012 में, संस्करण 3.0 लॉन्च किया गया था। हालाँकि, हेवन 4.0 को 2013 में रिलीज़ किया गया था। इसने कई छोटे सुधार पेश किए, जिनमें यूनीगाइन का एक और हालिया संस्करण शामिल है।"
        },

        "GeekBench 5 OpenCL": {
            "en": "Geekbench 5, a common benchmark for graphics cards, is made up of 11 test scenarios. These scenarios are based on the direct use of GPU's processing speed. No 3D rendering is required. OpenCL API from Khronos Group is used in this variation.",
            "de": "Geekbench 5, ein gängiger Benchmark für Grafikkarten, besteht aus 11 Testszenarien. Diese Szenarien basieren auf der direkten Nutzung der Verarbeitungsgeschwindigkeit der GPU. Es ist kein 3D-Rendering erforderlich. In dieser Variante kommt die OpenCL API der Khronos Group zum Einsatz.",
            "es": "Geekbench 5, un punto de referencia común para tarjetas gráficas, se compone de 11 escenarios de prueba. Estos escenarios se basan en el uso directo de la velocidad de procesamiento de la GPU. No se requiere representación 3D. En esta variación se utiliza la API OpenCL de Khronos Group.",
            "fr": "Geekbench 5, une référence commune pour les cartes graphiques, est composé de 11 scénarios de test. Ces scénarios sont basés sur l'utilisation directe de la vitesse de traitement du GPU. Aucun rendu 3D n'est requis. L'API OpenCL du groupe Khronos est utilisée dans cette variante.",
            "tr": "Grafik kartları için ortak bir kıyaslama olan Geekbench 5, 11 test senaryosundan oluşuyor. Bu senaryolar, GPU'nun işlem hızının doğrudan kullanımına dayanmaktadır. 3D render gerekmez. Bu varyasyonda Khronos Group'tan OpenCL API kullanılmıştır.",
            "zh": "Geekbench 5 是显卡的通用基准测试，由 11 个测试场景组成。这些场景都是基于直接利用GPU的处理速度。无需 3D 渲染。此变体中使用了来自 Khronos Group 的 OpenCL API。",
            "hi": "गीकबेंच 5, ग्राफिक्स कार्ड के लिए एक सामान्य बेंचमार्क, 11 परीक्षण परिदृश्यों से बना है। ये परिदृश्य जीपीयू की प्रसंस्करण गति के प्रत्यक्ष उपयोग पर आधारित हैं। किसी 3D रेंडरिंग की आवश्यकता नहीं है। ख्रोनोस ग्रुप से ओपनसीएल एपीआई इस भिन्नता में प्रयोग किया जाता है।"
        },

        "GeekBench 5 Vulkan": {
            "en": "Geekbench 5, a common benchmark for graphics cards, is made up of 11 test scenarios. These scenarios are based on the direct use of GPU's processing speed. No 3D rendering is required. This variant uses Vulkan API from AMD & Khronos Group.",
            "de": "Geekbench 5, ein gängiger Benchmark für Grafikkarten, besteht aus 11 Testszenarien. Diese Szenarien basieren auf der direkten Nutzung der Verarbeitungsgeschwindigkeit der GPU. Es ist kein 3D-Rendering erforderlich. Diese Variante verwendet die Vulkan-API von AMD & Khronos Group.",
            "es": "Geekbench 5, un punto de referencia común para tarjetas gráficas, se compone de 11 escenarios de prueba. Estos escenarios se basan en el uso directo de la velocidad de procesamiento de la GPU. No se requiere representación 3D. Esta variante utiliza la API Vulkan de AMD y Khronos Group.",
            "fr": "Geekbench 5, une référence commune pour les cartes graphiques, est composé de 11 scénarios de test. Ces scénarios sont basés sur l'utilisation directe de la vitesse de traitement du GPU. Aucun rendu 3D n'est requis. Cette variante utilise l'API Vulkan d'AMD & Khronos Group.",
            "tr": "Grafik kartları için ortak bir kıyaslama olan Geekbench 5, 11 test senaryosundan oluşuyor. Bu senaryolar, GPU'nun işlem hızının doğrudan kullanımına dayanmaktadır. 3D render gerekmez. Bu varyant, AMD & Khronos Group'tan Vulkan API'sini kullanır.",
            "zh": "Geekbench 5 是显卡的通用基准测试，由 11 个测试场景组成。这些场景都是基于直接利用GPU的处理速度。无需 3D 渲染。此变体使用来自 AMD 和 Khronos Group 的 Vulkan API。",
            "hi": "गीकबेंच 5, ग्राफिक्स कार्ड के लिए एक सामान्य बेंचमार्क, 11 परीक्षण परिदृश्यों से बना है। ये परिदृश्य जीपीयू की प्रसंस्करण गति के प्रत्यक्ष उपयोग पर आधारित हैं। किसी 3D रेंडरिंग की आवश्यकता नहीं है। यह वैरिएंट AMD और Khronos Group के Vulkan API का उपयोग करता है।"
        },

        "GeekBench 5 CUDA": {
            "en": "Geekbench 5, a common benchmark for graphics cards, is made up of 11 test scenarios. These scenarios are based on GPU processing power only. No 3D rendering is required. This variant uses CUDA API from NVIDIA.",
            "de": "Geekbench 5, ein gängiger Benchmark für Grafikkarten, besteht aus 11 Testszenarien. Diese Szenarien basieren nur auf der GPU-Rechenleistung. Es ist kein 3D-Rendering erforderlich. Diese Variante verwendet die CUDA-API von NVIDIA.",
            "es": "Geekbench 5, un punto de referencia común para tarjetas gráficas, se compone de 11 escenarios de prueba. Estos escenarios se basan únicamente en la potencia de procesamiento de la GPU. No se requiere representación 3D. Esta variante utiliza la API CUDA de NVIDIA.",
            "fr": "Geekbench 5, une référence commune pour les cartes graphiques, est composé de 11 scénarios de test. Ces scénarios sont basés uniquement sur la puissance de traitement du GPU. Aucun rendu 3D n'est requis. Cette variante utilise l'API CUDA de NVIDIA.",
            "tr": "Grafik kartları için ortak bir kıyaslama olan Geekbench 5, 11 test senaryosundan oluşuyor. Bu senaryolar yalnızca GPU işlem gücüne dayalıdır. 3D render gerekmez. Bu değişken, NVIDIA'nın CUDA API'sini kullanır.",
            "zh": "Geekbench 5 是显卡的通用基准测试，由 11 个测试场景组成。这些场景仅基于 GPU 处理能力。无需 3D 渲染。此变体使用 NVIDIA 的 CUDA API。",
            "hi": "गीकबेंच 5, ग्राफिक्स कार्ड के लिए एक सामान्य बेंचमार्क, 11 परीक्षण परिदृश्यों से बना है। ये परिदृश्य केवल GPU प्रोसेसिंग पावर पर आधारित हैं। किसी 3D रेंडरिंग की आवश्यकता नहीं है। यह संस्करण NVIDIA के CUDA API का उपयोग करता है।"
        },

        "SPECviewperf 12 - Maya": {
            "en": "This part of SPECviewperf12 workstation benchmark utilizes Autodesk Maya13 engine to render a static scene of a superpowered energy plant consisting of over 700,000 polygons in six modes.",
            "de": "Dieser Teil des SPECviewperf12-Workstation-Benchmarks verwendet die Autodesk Maya13-Engine, um eine statische Szene eines Energiekraftwerks mit Superkräften zu rendern, das aus über 700.000 Polygonen in sechs Modi besteht.",
            "es": "Esta parte de la evaluación comparativa de la estación de trabajo SPECviewperf12 utiliza el motor Autodesk Maya13 para representar una escena estática de una planta de energía con superpoderes que consta de más de 700 000 polígonos en seis modos.",
            "fr": "Esta parte de la evaluación comparativa de la estación de trabajo SPECviewperf12 utiliza el motor Autodesk Maya13 para representar una escena estática de una planta de energía con superpoderes que consta de más de 700 000 polígonos en seis modos.",
            "tr": "SPECviewperf12 iş istasyonu karşılaştırmasının bu bölümü, altı modda 700.000'den fazla çokgenden oluşan süper güçlü bir enerji santralinin statik bir sahnesini oluşturmak için Autodesk Maya13 motorunu kullanır.",
            "zh": "SPECviewperf12 工作站基准测试的这一部分利用 Autodesk Maya13 引擎以六种模式渲染由超过 700,000 个多边形组成的超级能源工厂的静态场景。",
            "hi": "SPECviewperf12 वर्कस्टेशन बेंचमार्क का यह हिस्सा ऑटोडेस्क माया13 इंजन का उपयोग छह मोड में 700,000 से अधिक बहुभुजों से युक्त एक महाशक्तिशाली ऊर्जा संयंत्र के स्थिर दृश्य को प्रस्तुत करने के लिए करता है।"
        },

        "SPECviewperf 12 - 3ds Max": {
            "en": "This benchmark simulates 3DS Max work, and executes eleven test scenarios in various uses, such as architectural modeling or animation for computer-games.",
            "de": "Dieser Benchmark simuliert die Arbeit mit 3DS Max und führt elf Testszenarien in verschiedenen Anwendungen durch, wie etwa Architekturmodellierung oder Animation für Computerspiele.",
            "es": "Este punto de referencia simula el trabajo de 3DS Max y ejecuta once escenarios de prueba en varios usos, como el modelado arquitectónico o la animación para juegos de computadora.",
            "fr": "Ce benchmark simule le travail de 3DS Max et exécute onze scénarios de test dans diverses utilisations, telles que la modélisation architecturale ou l'animation pour les jeux informatiques.",
            "tr": "Bu kıyaslama, 3DS Max çalışmasını simüle eder ve mimari modelleme veya bilgisayar oyunları için animasyon gibi çeşitli kullanımlarda on bir test senaryosu yürütür.",
            "zh": "该基准测试模拟 3DS Max 工作，并在各种用途中执行十一个测试场景，例如计算机游戏的建筑建模或动画。",
            "hi": "यह बेंचमार्क 3DS मैक्स कार्य का अनुकरण करता है, और कंप्यूटर गेम के लिए आर्किटेक्चरल मॉडलिंग या एनीमेशन जैसे विभिन्न उपयोगों में ग्यारह परीक्षण परिदृश्यों को निष्पादित करता है।"
        },

        "Unigine Heaven 4.0": {
            "en": "It is an older DirectX 11 benchmark. Unigine 3.0 has very few differences. The benchmark depicts a fictional medieval city spread over many flying islands. It is sometimes still used, even though it has a significant age.",
            "de": "Es ist ein älterer DirectX 11-Benchmark. Unigine 3.0 hat nur sehr wenige Unterschiede. Der Benchmark zeigt eine fiktive mittelalterliche Stadt, die sich über viele fliegende Inseln erstreckt. Es wird manchmal noch verwendet, obwohl es ein beträchtliches Alter hat.",
            "es": "Es un punto de referencia de DirectX 11 más antiguo. Unigine 3.0 tiene muy pocas diferencias. El punto de referencia representa una ciudad medieval ficticia repartida en muchas islas voladoras. A veces todavía se usa, aunque tiene una edad significativa.",
            "fr": "Il s'agit d'un ancien benchmark DirectX 11. Unigine 3.0 a très peu de différences. Le repère représente une ville médiévale fictive répartie sur de nombreuses îles volantes. Il est parfois encore utilisé, même s'il a un âge important.",
            "tr": "Daha eski bir DirectX 11 kıyaslamasıdır. Unigine 3.0'ın çok az farkı vardır. Kriter, birçok uçan adaya yayılmış kurgusal bir ortaçağ şehrini tasvir ediyor. Önemli bir yaşına rağmen bazen hala kullanılmaktadır.",
            "zh": "它是较旧的 DirectX 11 基准测试。 Unigine 3.0 几乎没有区别。该基准描绘了一个虚构的中世纪城市，分布在许多飞行岛屿上。它有时仍在使用，即使它已经有很长的历史了。",
            "hi": "यह एक पुराना DirectX 11 बेंचमार्क है। Unigine 3.0 में बहुत कम अंतर हैं। बेंचमार्क कई उड़ते हुए द्वीपों में फैले एक काल्पनिक मध्यकालीन शहर को दर्शाता है। यह कभी-कभी अभी भी प्रयोग किया जाता है, भले ही इसकी महत्वपूर्ण उम्र हो।"
        },

        "Octane Render OctaneBench": {
            "en": "It is a benchmark that measures graphics card performance using OctaneRender. OctaneRender is a real GPU rendering engine developed by OTOY Inc. and is available as a standalone or plugin for 3DS Max, Cinema 4D, and other applications. The benchmark renders four static scenes and then compares the render times to a reference GPU, currently GeForce GTX-980. The benchmark is not intended for gaming, but professionals working in 3D graphics.",
            "de": "Es ist ein Benchmark, der die Grafikkartenleistung mit OctaneRender misst. OctaneRender ist eine echte GPU-Rendering-Engine, die von OTOY Inc. entwickelt wurde und als Standalone oder Plugin für 3DS Max, Cinema 4D und andere Anwendungen erhältlich ist. Der Benchmark rendert vier statische Szenen und vergleicht dann die Renderzeiten mit einer Referenz-GPU, aktuell GeForce GTX-980. Der Benchmark ist nicht für Spiele gedacht, sondern für Profis, die mit 3D-Grafik arbeiten.",
            "es": "Es un punto de referencia que mide el rendimiento de la tarjeta gráfica utilizando OctaneRender. OctaneRender es un motor de renderizado de GPU real desarrollado por OTOY Inc. y está disponible como complemento o independiente para 3DS Max, Cinema 4D y otras aplicaciones. El punto de referencia renderiza cuatro escenas estáticas y luego compara los tiempos de renderizado con una GPU de referencia, actualmente GeForce GTX-980. El punto de referencia no está destinado a los juegos, sino a los profesionales que trabajan en gráficos 3D.",
            "fr": "C'est une référence qui mesure les performances de la carte graphique à l'aide d'OctaneRender. OctaneRender est un véritable moteur de rendu GPU développé par OTOY Inc. et est disponible en version autonome ou en plug-in pour 3DS Max, Cinema 4D et d'autres applications. Le benchmark rend quatre scènes statiques, puis compare les temps de rendu à un GPU de référence, actuellement GeForce GTX-980. La référence n'est pas destinée aux jeux, mais aux professionnels travaillant dans le graphisme 3D.",
            "tr": "OctaneRender kullanarak grafik kartı performansını ölçen bir kıyaslamadır. OctaneRender, OTOY Inc. tarafından geliştirilen gerçek bir GPU işleme motorudur ve 3DS Max, Cinema 4D ve diğer uygulamalar için bağımsız veya eklenti olarak mevcuttur. Kıyaslama, dört statik sahneyi işler ve ardından işleme sürelerini şu anda GeForce GTX-980 olan bir referans GPU ile karşılaştırır. Kıyaslama, oyun oynamak için değil, 3D grafiklerde çalışan profesyoneller için tasarlanmıştır.",
            "zh": "它是使用 OctaneRender 测量显卡性能的基准。 OctaneRender 是由 OTOY Inc. 开发的真正的 GPU 渲染引擎，可作为 3DS Max、Cinema 4D 和其他应用程序的独立或插件使用。该基准测试渲染了四个静态场景，然后将渲染时间与参考 GPU（目前为 GeForce GTX-980）进行比较。该基准测试不适用于游戏，而是用于 3D 图形领域的专业人士。",
            "hi": "यह एक बेंचमार्क है जो ऑक्टेनरेंडर का उपयोग करके ग्राफिक्स कार्ड के प्रदर्शन को मापता है। OctaneRender OTOY Inc. द्वारा विकसित एक वास्तविक GPU रेंडरिंग इंजन है और यह 3DS Max, Cinema 4D और अन्य अनुप्रयोगों के लिए स्टैंडअलोन या प्लगइन के रूप में उपलब्ध है। बेंचमार्क चार स्थिर दृश्यों को रेंडर करता है और फिर रेंडर समय की तुलना संदर्भ जीपीयू से करता है, वर्तमान में GeForce GTX-980। बेंचमार्क गेमिंग के लिए नहीं है, बल्कि 3डी ग्राफिक्स में काम करने वाले पेशेवर हैं।"
        },

        "GeekBench 5 Metal": {
            "en": "Geekbench 5, a common benchmark for graphics cards, is made up of 11 test scenarios. These scenarios are based on GPU processing power only. No 3D rendering is required. This variant uses the Metal API from Apple.",
            "de": "Geekbench 5, ein gängiger Benchmark für Grafikkarten, besteht aus 11 Testszenarien. Diese Szenarien basieren nur auf der GPU-Rechenleistung. Es ist kein 3D-Rendering erforderlich. Diese Variante nutzt die Metal API von Apple.",
            "es": "Geekbench 5, un punto de referencia común para tarjetas gráficas, se compone de 11 escenarios de prueba. Estos escenarios se basan únicamente en la potencia de procesamiento de la GPU. No se requiere representación 3D. Esta variante utiliza la API Metal de Apple.",
            "fr": "Geekbench 5, une référence commune pour les cartes graphiques, est composé de 11 scénarios de test. Ces scénarios sont basés uniquement sur la puissance de traitement du GPU. Aucun rendu 3D n'est requis. Cette variante utilise l'API Metal d'Apple.",
            "tr": "Grafik kartları için ortak bir kıyaslama olan Geekbench 5, 11 test senaryosundan oluşuyor. Bu senaryolar yalnızca GPU işlem gücüne dayalıdır. 3D render gerekmez. Bu değişken, Apple'ın Metal API'sini kullanır.",
            "zh": "Geekbench 5 是显卡的通用基准测试，由 11 个测试场景组成。这些场景仅基于 GPU 处理能力。无需 3D 渲染。此变体使用 Apple 的 Metal API。",
            "hi": "गीकबेंच 5, ग्राफिक्स कार्ड के लिए एक सामान्य बेंचमार्क, 11 परीक्षण परिदृश्यों से बना है। ये परिदृश्य केवल GPU प्रोसेसिंग पावर पर आधारित हैं। किसी 3D रेंडरिंग की आवश्यकता नहीं है। यह वैरिएंट Apple के मेटल API का उपयोग करता है।"
        }
    }


def get_translated_test_description(name, language):
    return data.get(name, {}).get(language, '-')
