# Generated by Django 4.1.5 on 2023-02-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('performance', models.FloatField(blank=True, default=0.0, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=255, null=True)),
                ('general_info', models.JSONField(blank=True, default=list, null=True)),
                ('technical_specs', models.JSONField(blank=True, default=list, null=True)),
                ('compatibility_dimensions_requirements', models.JSONField(blank=True, default=list, null=True)),
                ('memory', models.JSONField(blank=True, default=list, null=True)),
                ('video_outputs_ports', models.JSONField(blank=True, default=list, null=True)),
                ('technologies', models.JSONField(blank=True, default=list, null=True)),
                ('api_support', models.JSONField(blank=True, default=list, null=True)),
                ('tests', models.JSONField(blank=True, default=list, null=True)),
                ('fps', models.JSONField(blank=True, default=list, null=True)),
                ('relative_performance', models.JSONField(blank=True, default=list, null=True)),
                ('equivalent_gpu', models.JSONField(blank=True, default=list, null=True)),
                ('similar_gpu', models.JSONField(blank=True, default=list, null=True)),
                ('rec_processor', models.JSONField(blank=True, default=list, null=True)),
                ('presets', models.JSONField(blank=True, default=list, null=True)),
                ('games', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
