# Generated by Django 4.1.5 on 2023-02-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuspecs',
            name='graph_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
