# Generated by Django 4.1.5 on 2023-02-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gpuspecs_graph_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuspecs',
            name='amzn_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
