# Generated by Django 4.0.3 on 2023-04-05 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gpuspecs_amzn_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuspecs',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
